### ISSUE TITLE
OSError: [Errno 28] Can't write data (file write failed: time = Wed Nov 30 22:27:02 2022

### ISSUE THREAD

**Issue by BenSamy2020** [Noble-Lab/casanovo#103]
Greeting,

While running casanovo using denovo mode on my institutes HPC I faced and error. I suspect that it might be a storage space issue. Can I confirm with you if it is a storage space issue before contacting my HPC to request for more storage?

Please refer to the attatched log below the error in detail. 

Regards,
Ben
 
[Casanovo_Log_with_Error.txt](https://github.com/Noble-Lab/casanovo/files/10128533/Casanovo_Log_with_Error.txt)

**Comment by wsnoble** [comment]
The error message 'No space left on device' seems definitive. Seems like you need to ask for more space.

**Comment by BenSamy2020** [comment]
Greetings,

On the last line of the log the message was - 
"filename = '/tmp/tmpy1v8xnxh/c90e3ad17a024dceb83502ce09231f83.hdf5', file descriptor = 11, errno = 28, error message = 'No space left on device', buf = 0x7fba9f4999f8, total write size = 105727680, bytes this sub-write = 105727680, bytes actually written = 18446744073709551615, offset = 0)"

Based on the error log, does this mean that Casanovo needs > 18446744073709551615 bytes (18446744073.709552765 GB)?

**Comment by bittremieux** [comment]
The `18446744073709551615` is likely incorrect because your computer couldn't handle being completely out of disk space. Casanovo actually tried to use 105727680 bytes = 105 MB for the 6 peak files you ran it on.

Casanovo will always try to write to the temporary directory (depending on where that is for your operating system). This behavior cannot be modified, so I recommend trying to run on a node with a larger temporary disk.
