### ISSUE TITLE
Casanovo confidently predicts short peptide sequences (< 5 aa)

### ISSUE THREAD

**Issue by RowanNelson** [Noble-Lab/casanovo#107]
Casanovo will occasionally very confidently predict very short peptides, with high mass differences. 
Attached is a zip archive with an .mgf with 72 spectra that the non-enzymatic model predicts to be less than 5 aa long, as well as the predictions from that model. Base model predictions are included as well, though the base model fares much better with these spectra.

[short-predictions.zip](https://github.com/Noble-Lab/casanovo/files/10173443/short-predictions.zip)

**Comment by wsnoble** [comment]
This problem is not specific to the non-enzymatic model.  Here are the top negative scores and corresponding sequences from the human data in the nine-species benchmark:

```
awk -F "\t" '($1 != "MTD") && ($9 < 0) {print $9 "\t" $2}' mskb_human_nb10.mztab | sort -n | head
-9.736418724060059e-05  TR
-9.47117805480957e-05   VK
-9.052455425262451e-05  FSLK
-8.469820022583008e-05  SK
-5.841255187988281e-05  C+57.021R
-5.768239498138428e-05  PLLK
-5.487600962317263e-05  C+57.021LR
-5.383150918147894e-05  VLGSC+57.021LK
-4.690885543823242e-05  TR
-3.993511199951172e-05  C+57.021LC+57.021K
```

The corresponding prediction file is in /net/noble/vol1/home/melih/denovo/poligon/debug/beam_search_check/curr_output/9species_benchmark_output/9-species_mztab/

We need to understand why Casanovo is so confident about these absurd predictions.

**Comment by wsnoble** [comment]
One potential "solution" (hack) would be to disallow putting a stop token into any sequence shorter than, say, 7 amino acids.  Or, better, disallow stop tokens before we reach the left edge of the precursor m/z window. How hard would either of these be to implement?

**Comment by wfondrie** [comment]
It would be easy for the greedy decoding, but significantly more difficult for the beam search decoding. Ideally both strategies would only ever return peptides within the precursor mass range.

**Comment by wsnoble** [comment]
It might be worth checking whether the problem occurs with greedy decoding.  E.g., run the above awk command on a file of predictions made with greedy.

**Comment by melihyilmaz** [comment]
Running the same awk command on Casanovo for the same human dataset but using `n_beams=1`, there are no such short peptides:

mzTab file: `/net/noble/vol1/home/melih/denovo/poligon/debug/beam_search_check/curr_output/9species_benchmark_output/mskb_human_nb1.mztab`

```
-0.7175224837966454	Q+0.984KLEEEKEELANTLASLGLLSVTSLEDLLVDEKELSFNK
-0.7125106000087478	VNQRPEDLPELEELTC+57.021QDGHLK
-0.7115336736214573	TGTVDVDSLLHLDDLDDGLLGYAKPYLKR
-0.7066795085556805	C+57.021GSLKPTLSENEDLSC+57.021
-0.6867479268800128	LLLTAGPSLGK
-0.6844119764864445	LDDGC+57.021DLLSLLEGLDLLGTDTVELFVLNPHEDLDLELLLEESPK
-0.6819048555273759	QVAAAALATLNSQSPPQLR
-0.6780666813254357	LALEDDGRLALLC+57.021DR
-0.6769018879532813	NGQQHLSNLALDLDDDLSGHVGLVK
-0.6701870554167291	SLLGDPSTEPDPVPGPVNAQEER
```

**Comment by wsnoble** [comment]
Wout says this happens when Casanovo is confident of the first few amino acids, but then there is no good-scoring amino acid and the stop token randomly gets selected. One solution would be to include the stop token in the peptide score, which would give a low score. Maybe we should include the stop token in general, since we expect that the model will be confident about being finished predicting.

What do we do when decoding stops because we exceed the precursor m/z?  Do we penalize the model for not predicting a stop token?  E.g., give the subsequent amino acid a score of 0, and include it in the average. Whether this helps is an empirical question.

Conclusion: we should change the scoring to include the stop token.  I.e., take the average over n+1.  We need to verify that this doesn't affect the behavior on a relatively large dataset before merging. Melih will evaluate on the 9-species benchmark after Wout implements it.
