### ISSUE TITLE
Modifications and their representations in revised 9-species benchmark

### ISSUE THREAD

**Issue by irleader** [Noble-Lab/casanovo#125]
Hi,

For [MSV000090982](https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?accession=MSV000090982) dataset, are there any N-terminal modifications? How are they represented in the mgf files?

I see the representation of Asn deamidation("N+0.984") as N[0.98] which is different than that in config.yaml. "M+15.995" as M[15.99], "Q+0.984" as Q[0.98].
Also, "C+57.021" is no longer there, does "C" represent "C+57.021" by default?

Thanks!

**Comment by wsnoble** [comment]
The truncation of mods to 2 digits after the decimal is a known issue with Tide output, which was fixed on [16 December 2022](http://crux.ms/release-notes.html).  Sorry for the inconvenience.

Yes, in Tide output, the +57.027 on C is implicit.

The missing N-terminal mods is worrisome.  They were specified when creating the index; we will investigate why they are not showing up in the search results.

**Comment by irleader** [comment]
Thanks a lot for letting me know. I am very looking forward to the new release of revised 9-species benchmark with N-terminal modifications added.

**Comment by wsnoble** [comment]
Update on the N-terminal mods: this was actually a ([known issue](https://github.com/crux-toolkit/crux-toolkit/issues/603) with the Tide search engine. We are regenerating the benchmark and will post an update here when it's available.

**Comment by bittremieux** [comment]
We have updated the benchmark data with the corrected peptide sequences (incl. N-terminal modifications). The MGF files are available in dataset [MSV000090982](https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?accession=MSV000090982) in the `/MSV000090982/updates/2023-03-08_woutb_2c43c18c/peak/9speciesbenchmark` FTP directory.

**Comment by irleader** [comment]
I am now using MSV000090982 to do benchmarking, if I do not need N-terminal modifications, would you suggest to use the first version or the updated version (and removing those PSM containing N-terminal modifications)?

As in my understanding, the updated version only includes extra N-terminal modifications in the Tide search. And there is nothing wrong with the first version in the Tide search, that's why the first version is still kept in the  massive [link](https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?accession=MSV000090982).

**Comment by bittremieux** [comment]
Definitely the updated benchmark, and then exclude PSMs you're not interested in. The big motivation to recreate the nine-species dataset was that the original DeepNovo version erroneously didn't consider some PTMs, and thus several of the peptide identifications are incorrect. So if you're using the initial version, you'll train and evaluate models on wrong data. Unfortunately for our first upload we mistakenly used an earlier version of the data that was processed with incomplete settings. Because MassIVE doesn't allow to remove or replace files, this version is still available online, but ideally shouldn't be used.

**Comment by tuanle618** [comment]
Hey @bittremieux,

I am currently using the newest Nine Species benchmark from the path `/MSV000090982/updates/2023-03-08_woutb_2c43c18c/peak/9speciesbenchmark` and noticed some key errors when I am tokenizing the peptide sequences.

E.g., using the dictionary provided in the current config.yaml (https://github.com/Noble-Lab/casanovo/blob/main/casanovo/config.yaml) certainly fails for several peptides.

I am showing some elements of failed sequences
`['R.GGYYSEGPAAEMEM[15.9949]GHR.Y',
 'K.Q[-17.0265]ISLFAENKPGR.L',
 'R.Q[-17.0265]GVIGDGQVGVTSYVVPK.G',
 'K.E[-17.0265]NGGVEAVEQR.N',
 'R.YEAIGGISPLAQITEQQAHN[0.9840]LEQHLNEIQDEITFK.A']`

The tokenizer which casanovo uses from depthcharge v0.2.3 does not contain the regex to extract the tokens correctly (see here).

For example, using the first sequence returns me the following elements
`re.split(r"(?<=.)(?=[A-Z])", 'R.GGYYSEGPAAEMEM[15.9949]GHR.Y')` returns 
`['R.',
 'G',
 'G',
 'Y',
 'Y',
 'S',
 'E',
 'G',
 'P',
 'A',
 'A',
 'E',
 'M',
 'E',
 'M[15.9949]',
 'G',
 'H',
 'R.',
 'Y']`

I do not find 'M[15.9949]' in the config.yaml from the default casanovo config.yaml, but `"M+15.995"`.

Other elements which I cannot see in the config.yaml are `Q[-17.0265]` (assuming the regex is correct).
Would this corresponds to tokens `Q` and `-17.0265` where the last would correspond to `-17.027` from the config https://github.com/Noble-Lab/casanovo/blob/main/casanovo/config.yaml#L134 ?

Find below the failed sequences when applying the regex and the following residues-list

    `residues = {
        "G": 57.021464,
        "A": 71.037114,
        "S": 87.032028,
        "P": 97.052764,
        "V": 99.068414,
        "T": 101.047670,
        "C+57.021": 160.030649, # 103.009185 + 57.021464
        "L": 113.084064,
        "I": 113.084064,
        "N": 114.042927,
        "D": 115.026943,
        "Q": 128.058578,
        "K": 128.094963,
        "E": 129.042593,
        "M": 131.040485,
        "H": 137.058912,
        "F": 147.068414,
        "R": 156.101111,
        "Y": 163.063329,
        "W": 186.079313,
        # Amino acid modifications.
        "M+15.995": 147.035400,   # Met oxidation:   131.040485 + 15.994915
        "N+0.984": 115.026943,     # Asn deamidation: 114.042927 +  0.984016
        "Q+0.984": 129.042594,    # Gln deamidation: 128.058578 +  0.984016
        # N-terminal modifications.
        "+42.011": 42.010565,      # Acetylation
        "+43.006": 43.005814,     # Carbamylation
        "-17.027": -17.026549,     # NH3 loss
        "+43.006-17.027": 25.980265,      # Carbamylation and NH3 loss,
        "C": 160.030649,
        "M[15.99]": 147.035400,
        "N[0.98]": 115.026943,
        "Q[0.98]": 129.042594,
    }`

[failed_train.txt](https://github.com/user-attachments/files/15526262/failed_train.txt) (~22MB, since these contain 670,538 failed sequences from the 9species benchmark set, except for the Apis-mellifera subset)

So my question is, is the regex should be updated? Or if the modification list is currently not up-to-date? 

Thank you in advance.

**Comment by bittremieux** [comment]
Yes, the first uploaded of the revised nine-species benchmark data was not fully formatted correctly. This has since been fixed, see the [information in the FAQ](https://casanovo.readthedocs.io/en/latest/faq.html#training-casanovo).

**Comment by tuanle618** [comment]
Ah gotcha. Thanks a lot! I will download the new updated (`2024-05-14_woutb_71950b89`) folder again. The updated dataset should be compatible with the registered tokens in the casanovo config file, right?

**Comment by tuanle618** [comment]
Hi @bittremieux, I was able process the data from the revised nine-species benchmark dataset (`2024-05-14_woutb_71950b89`). I just noticed that there is one peptide sequence which fails to be tokenized.
It is the following `LAQFYGLPAFVAGTOSDAK` which gets to the KeyError `O` not found in the default residues config.

**Comment by wsnoble** [comment]
Oops -- that keyerror is due to a pyrrolysine, which Tide knows about but Casanovo doesn't.  This may also happen with selenocysteine (U). Thanks for letting us know -- we will fix this.

**Comment by bittremieux** [comment]
This has now been fixed and the corresponding file has been updated at `MSV000090982/updates/2024-05-14_woutb_71950b89/peak/9speciesbenchmark/Methanosarcina-mazei/Mm2DLC_N_1_01.mgf`. Thank you for letting us know.

**Comment by tuanle618** [comment]
Awesome. Thank you!
