### ISSUE TITLE
Questions about comparing de novo methods

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#133]
[From an email from a Casanovo user]

I developed a new tool for peptide de novo sequencing and would like to compare its performace with Casanovo.But I have two questions regarding using Casanovo and analyzing its outputs.

First, I would like to compare Casanovo with my tool on the 9-species data set ([ftp://Nancyzxll:DeepNovo2017@massive.ucsd.edu](https://urldefense.com/v3/__ftp://Nancyzxll:DeepNovo2017@massive.ucsd.edu__;!!K-Hz7m0Vt54!ibSl8ocomIflehKTr7GBJfPvsiHZsHxQzOPeQ0ebcu_st0hTbgavf5D3_tAn9mST-A6yijN1rPQYkBR00XE$) ) originally provided in the DeepNovo/PointNovo papers. Casanovo provides a model file named "casanovo_massivekb.ckpt" for de novo sequencing. May I directly use this model to predict peptide sequences for MS/MS spectra in the above data set? Or would you recommend a more proper way like DeepNovo/PointNovo did and may I obtain the nine models when Casanovo performed the cross-species benchmarking If these nine models can't be provided, would you like to share the de novo results for this 9-species data set?

Second, I analyzed a Casanovo output file and didn't find the corresponding MS/MS spectrum for a peptide identification entry. How can I acquire this information from the Casanovo output?

**Comment by melihyilmaz** [comment]
1) They can use directly use `casanovo_massivekb.ckpt` to compare run Casanovo but if they want the weights trained on the original benchmark, referred to as `Casanovo_bm` in the manuscript, 9 sets of weights corresponding to cross validation splits are [here](https://zenodo.org/record/6791263) on Zenodo.
2) Latest PR #105 solves spectrum ID tracking

**Comment by boluosuannai** [comment]
Thank you very much for your answer, which is very helpful to me, but I have encountered new problems. I have downloaded the 9 sets of weights corresponding to cross validation on Zenodo. But when I was running Casanovo(version 3.2.0), something went wrong:
<img width="1369" alt="59fb5ab97f0d04cfcb7b748a4294c35" src="https://user-images.githubusercontent.com/49779783/216823112-6a2d9ed8-8fd7-404d-93b1-a5f700007e45.png">
So I checked the historical version of Casanovo and found that the pre-trained weights for the nine species should correspond to version 2.1.1, how do I run Casanovo2.1.1.

**Comment by bittremieux** [comment]
Clarification for point (2): spectra will always be reported in the output file, the recent PR only fixes how they are indexed (by scan number (new) or index (old)). The only time that spectra will not be included in the output file is if they are very low quality and don't pass our preprocessing filter.
To get the updated spectrum indexing functionality you will currently need to install Casanovo from `main` on GitHub, until we release a new version (soon).

To run Casanovo 3.+ with the old weights, use a custom `config.yaml` file with the [N-terminal modifications removed](https://github.com/Noble-Lab/casanovo/blob/main/casanovo/config.yaml#L77). The difference is that Casanovo 2.x was trained without any N-terminal modifications, hence, there's a mismatch in the model weights.

Nevertheless, using the nine-species model weights will give a pessimistic view of the Casanovo performance, because we know that the model only reaches optimal performance when trained on a larger dataset. Hence, the `casanovo_massivekb.ckpt` weights will give significantly better results.
