### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.lite'

### ISSUE THREAD

**Issue by rostkick** [Noble-Lab/casanovo#161]
After installation on `Ubuntu 20.04.3 LTS` or on `MacOS 11.5.2`, when I call `casanovo --help` I get an error:  
`ModuleNotFoundError: No module named 'pytorch_lightning.lite'`. 
Is there any way to fix this? I assume is needed to downgrade the pytorch version, but I have not been able to solve this problem. Maybe you should create a requirements file with the exact versions of the packages used, or create a docker image for a more stable installation?

**Comment by bittremieux** [comment]
Casanovo indeed doesn't work with the recently released version 2.0 of PyTorch Lightning. This has already been fixed in the development version and will be included in the next release very soon. For now, a workaround is to downgrade PyTorch Lightning to version 1.9: `pip install --force-reinstall pytorch-lightning==1.9`.
