### ISSUE TITLE
FDR scoring mzTab output

### ISSUE THREAD

**Issue by patrick-willems** [Noble-Lab/casanovo#170]
Hey,

First of all thanks for the great tool!

I was currently testing it on some data. To acquire a target-decoy FDR score for PSM identifications in the mzTab output, would it be sensible to assign peptides as target/decoy/none and run Percolator on the PSMs that were assigned as target/decoy? This could then define a search_engine_score at a FDR of 0.01 to filter the mzTab output. I think something similar was used in the preprint? Or what would be your suggestion.

Thanks in advance,
Patrick

**Comment by bittremieux** [comment]
There is no established method for FDR control in _de novo_ searching. As _de novo_ is database-free by definition, it is inherently impossible to assign peptides as targets or decoys, and thus standard approaches for FDR control cannot be used. This problem is not unique to Casanovo, but applies to every application of _de novo_ peptide sequencing.
