### ISSUE TITLE
assembly cutoff

### ISSUE THREAD

**Issue by biocc** [Noble-Lab/casanovo#182]
Does Casanovo have an common assembly threshold? Similar to what the authors of DeepNovo suggest, excluding peptides with a confidence score below 50 can improve the quality of the assembly by removing sequence contaminants from de novo sequencing results.

**Comment by bittremieux** [comment]
No, Casanovo will report the best-scoring peptide(s) for each spectrum, without any score cut-off.

Note though that the scores for predictions that don't fit the precursor mass tolerance are penalized such that those PSMs always have a lower score than any PSM that fits the precursor mass tolerance.

Thresholding is left to the user, depending on how stringent they want to be. As there is no good way for confidence estimation during _de novo_ searching, such as target-decoy for sequence database searching, rather than using heuristics to instill a false sense of confidence in the results, Casanovo leaves that decision to the user.
