### ISSUE TITLE
Casanovo Errors in Eval Mode

### ISSUE THREAD

**Issue by justin-a-sanders** [Noble-Lab/casanovo#216]
Running Casanovo in eval mode gives the following error: 

> File "/usr/local/lib/python3.10/dist-packages/casanovo/denovo/model_runner.py", line 128, in _execute_existing out_writer.set_ms_run(peak_filenames)
> 
> AttributeError: 'NoneType' object has no attribute 'set_ms_run'

You can reproduce using the simple one-spectrum example laid out in this notebook: 
https://colab.research.google.com/github/Noble-Lab/casanovo_asms2023/blob/main/Casanovo_Tutorial.ipynb#scrollTo=b7yHuyE17Awf

**Comment by wfondrie** [comment]
Is this a problem in the `dev` branch as well? We did a major refactor there and I suspect it may be solved.

**Comment by wsnoble** [comment]
I believe that it is not in the dev branch.  But the issue was posted in response to my suggestion (on Slack) that we consider rescinding release 3.4.0 because it doesn't seem to work.  While we work on getting the dev branch to be functional, I thought maybe we should either revert to 3.3 or push a 3.5 that runs successfully.
