### ISSUE TITLE
Changing Modifications in configuration file

### ISSUE THREAD

**Issue by lutfia95** [Noble-Lab/casanovo#227]
Dear Authors, 

thank you very much for providing casanovo. I was trying to train new casanovo model using the Human HCD spectral library (containing 1,114,503 peptides). I split the data set into 99:1. I changed the modifications in the configuration file of casanovo to use only C and M (Oxidation), because I am interested only in identifying these modifications. The training data set contains sequences which also have Q and N and some others. But as I am interested in only two modifications assigned in the configuration file of casanovo, this should be no problem correct? 
When I started the training process, casanovo showed these modifications as input modifications:

`residues = {'G': 57.021464, 'A': 71.037114, 'S': 87.032028, 'P': 97.052764, 'V': 99.068414, 'T': 101.04767, 'C+57.021': 160.030649, 'L': 113.084064, 'I': 113.084064, 'N': 114.042927, 'D': 115.026943, 'Q': 128.058578, 'K': 128.094963, 'E': 129.042593, 'M': 131.040485, 'H': 137.058912, 'F': 147.068414, 'R': 156.101111, 'Y': 163.063329, 'W': 186.079313, 'M+15.995': 147.0354, 'N+0.984': 115.026943, 'Q+0.984': 129.042594, '+42.011': 42.010565, '+43.006': 43.005814, '-17.027': -17.026549, '+43.006-17.027': 25.980265}`  

Attached is my configuration file ([config.yml.txt](https://github.com/Noble-Lab/casanovo/files/12267464/config.yml.txt))
This is also the log file of the training start:  [log.txt](https://github.com/Noble-Lab/casanovo/files/12267478/log.txt)

After finishing the training, I tested the model with the used configuration file and unfortunately other modifications are identified! 

Should I remove all peptides from the training set, which contain other modifications?! I though that identifying the modifications in the configuration file should be the input for the model. 

Thank you very much for your support! 
Best,

Ahmad

**Comment by bittremieux** [comment]
Hi Ahmad, yes, you have to make sure that your training set only contains known modifications. This is not because otherwise Casanovo will pick up extra modifications from the data, but because it won't know how to parse unknown modifications and crash.

I suspect somehow your config file still contained the initial modifications., because the residues are still specified in their original form (e.g. `M+15.995`), whereas your specification is formatted slightly differently (e.g. `M(+15.99)`). Can you double-check that the correct config file is used when you're training Casanovo?

That being said, I don't think retraining is necessary for the use case you describe. The existing model was trained on 30 million PSMs, more than an order of magnitude more data than you're using, and should perform significantly better. If the data doesn't contain specific modifications, Casanovo shouldn't predict those either, or if you really want, you can filter out those predictions afterwards.

In general retraining is only necessary when you want to identify _novel_ PTMs.

**Comment by bittremieux** [comment]
There was actually a bug in Casanovo that prevented the custom residues being loaded (see #228). This has now been fixed, so retraining Casanovo with custom PTMs will be possible in the next version. Thanks for reporting the issue. In your case I would still recommend to just use the default Casanovo model though.

**Comment by lutfia95** [comment]
Hi @bittremieux, 


sorry for the late response, I was checking the configuration file and browsing the code and yes I found the same thing as #228 I will go with your option and remove the modifications afterwards, which I don't want. E.g. `AAAACCM+15.995KL`, removing the modification means removing the whole amino acid related to `M+15.995`or only removing the value of the modification `M+15.995`? It might be also interesting for me, if you have an list of the trained modifications, so that I can save the time to train other model, when I can remove the modifications afterwards, which I don't need. Is the new fixed version useable? or should I make the changes directly to source and then rebuild Casanova manually? 


Best,
Ahmad

**Comment by bittremieux** [comment]
It means discarding the whole PSM; modifying only a single amino acid will invalidate Casanovo's identification.

Potentially you can obtain multiple PSMs per peptide (by setting the [`top_match`](https://github.com/Noble-Lab/casanovo/blob/main/casanovo/config.yaml#L105) parameter t > 1) and select the highest scoring PSM that doesn't contain one of the PTMs you don't like.

All of the modifications that Casanovo knows are listed in the config file, and also reported in the log when you run Casanovo (the snippet you posted in the first message). So you can post-process the data based on those PTMs.

The fix hasn't been included in a new release yet because we're still going through some code reviews, but it will be available soon.

**Comment by bittremieux** [comment]
Casanovo v.3.5.0 including this fix is now available. Thank you for your patience.
