### ISSUE TITLE
Casanovo v4.1.0: RuntimeError about NVIDIA driver even CPU mode

### ISSUE THREAD

**Issue by progistar** [Noble-Lab/casanovo#302]
`RuntimeError: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.`

I used CPU mode, but the RuntimeError was occurred.
I think it is not serious issue; however, it would be great to fix it.

Thank you for your effort in advance!

**Comment by bittremieux** [comment]
This error originates from PyTorch/PyTorch Lightning and because our code doesn't trigger it, but rather underlying PyTorch, unfortunately we can't avoid it.

As a workaround, you can "hide" the GPU when running Casanovo by setting `CUDA_VISIBLE_DEVICES` to an empty value. E.g.:
```
CUDA_VISIBLE_DEVICES="" casanovo ...
```

With `...` the Casanovo command you want to execute.

I think that this should work.

**Comment by progistar** [comment]
@bittremieux Thank you for your quick reply! It really helps me!
