### ISSUE TITLE
.d to mgf conversion for de novo

### ISSUE THREAD

**Issue by jonathan-krieger-bruker** [Noble-Lab/casanovo#50]
Hi,
I'd like to use a timsTOF .d file as an input. I've tried converting this to a .mgf with multiple tools yet I continually get an error.  How can I process this?
Below is a screenshot of the error I get.
Thank you,
Jonathan
![image](https://user-images.githubusercontent.com/96065891/181400043-b6bfcb1e-747f-4644-a65d-e081ad308cc1.png)

**Comment by wsnoble** [comment]
Can you post a sample of one of your mgf files, or even just the first 1000 lines of such a file?

**Comment by bittremieux** [comment]
The problem seems to be that your MGF file is missing some information, in this case the precursor charges of the MS/MS spectra. Unfortunately I'm not sufficiently familiar to know whether it is expected that this information is not available for timsTOF data, but for successful spectrum identification Casanovo does require it.

The most straightforward solution would be to figure out how to include the precursor charges in the MGF export, although unfortunately I can't directly recommend the best tool to do this.

**Comment by wfondrie** [comment]
My guess is that it is charge is called something else in @jonathan-krieger-bruker's file. A sample of the file's content should help us out.

**Comment by jonathan-krieger-bruker** [comment]
Hi all - thanks for helping to look into this.  I tested 2 MGF files created different ways but they both look quite different then the test file or preprocessed data provided in the repo.  I attach a zip file of these 2 MGFs (Top ~1000 lines or so).
Thanks again!
Jonathan
[MGF_samples.zip](https://github.com/Noble-Lab/casanovo/files/9212377/MGF_samples.zip)
.

**Comment by jonathan-krieger-bruker** [comment]
The Charge state seems to be there and seems to be written in the same way as the test data. However the intensity values are very different - one looks relative and one looks absolute?

**Comment by bittremieux** [comment]
Relative vs absolute intensity values shouldn't make a difference because intensities are normalized by Casanovo anyway.

In fact, I could run Casanovo successfully on the two example files you provided. I'm guessing that not all spectra are incorrect, and the one Casanovo chokes on is further down in the file you're trying to process. Would it be possible to share the full MGF with which you got the error so I can further debug the issue? Thanks.

**Comment by treitpeter** [comment]
Hello, 
Has this been solved? And if yes, are there any recommendations as to how to convert .d to mgf so that things work? 
Best, 
Peter

**Comment by bittremieux** [comment]
As far as we are aware this should work. If you do encounter problems, please let us know and share the relevant information to diagnose the issue.

**Comment by treitpeter** [comment]
Hello, 
I'm trying to run casanovo on some pulldown samples, i.e. I shouldn't have too many proteins in the runs.
I tried to convert our .d files to both .mzml (both scan summing and non-scann summing didnt work) and eventually .mgf with peakpicking turned on in msconvert. I included peakpicking according to this article (https://fragpipe.nesvilab.org/docs/tutorial_convert.html).

I get the following error:

2025-04-04 23:17:14,823 INFO [depthcharge.data.hdf5/MainProcess] hdf5.__init__ : Reading 1 files...
2025-04-04 23:17:34,242 WARNING [depthcharge.data.parsers/MainProcess] parsers.read : Skipped 1306 spectra with invalid precursor info
2025-04-04 23:18:13,005 INFO [casanovo/MainProcess] model._get_top_peptide : No peptides found for spectrum 371
... and then no peptides found for many more spectra.

I'm not sure how to interpret this - for some spectrum we had precursor info or not?
Is there an error in how I generate the mgf or mzml, is there a gold standard to convert .d files? I have several more projects for which I would be keen to test.

**Comment by pgarrett-scripps** [comment]
I ran into the same problem with Casanovo and Bruker files - pretty sure msconvert was the culprit.

Ended up writing a custom mgf extractor that might be useful for others: https://github.com/pgarrett-scripps/tdfextractor

It has a --casanovo flag that shrinks the mgf files by doing the same filtering as the Casanovo paper (top 150 peaks, precursor removal, 50-2500 m/z range). @bittremieux does this seem like a reasonable approach? My mgf files were huge without it.

**Comment by wsnoble** [comment]
Yes, that seems like a reasonable approach, as long as you verify that you do those steps in the same order as Casanovo does.

**Comment by pgarrett-scripps** [comment]
I was initially trying to convert to mgf with msconvert with 'combine ion mobility scans'. But looking closer it seems that the resulting peaks within each spectra are not sequential and there seems to be many duplicate peaks (I assume from the 10 or so tof scans being combined per spectra). I would expect 'combine ion mobility scans' to combine and merge the tof scans, but this didn't seem to be the case for me. 

I was comparing my tool (with the --casanovo arg) to msconvert, but this isn't really a fair comparison. The actual effect of using the casanovo pre filtering is not as substantial (3-4x)

**Average MGF File Size:**

- msconvert: 2.5GB
- tdfextractor --casanovo: 100 MB
- tdfextractor: 350 MB

**Comment by bittremieux** [comment]
Based on some preliminary experiences in my lab, ion mobility data definitely needs to be merged. Otherwise the individual scans are of lower quality, hindering good Casanovo results. I'm not super familiar with msconvert's merging procedure, but having duplicate peaks is problematic for a few different reasons in Casanovo, including that it would mess up the top-k peak selection. So there definitely needs to be some preprocessing on the spectra then.

Ultimately we'd like to have native .d file reading capabilities, and thus also appropriately handling ion mobility data. This is not on our immediate development roadmap, however. So if you have any good instructions or a guide for other users that we could put in the FAQ, that would be highly appreciated.

**Comment by bittremieux** [comment]
Awesome, thanks. For the documentation, a PR to `main` is best, then it's immediately reflected in the FAQ.

A PR with native .d support would also be highly appreciated. This should be implemented in [DepthCharge](https://github.com/wfondrie/depthcharge/) rather than Casanovo directly though, because that's where the file IO occurs.
